In [1]:
import os
import rippl_AI
import importlib
importlib.reload(rippl_AI)
import aux_fcn

import matplotlib.pyplot as plt
import numpy as np
%matplotlib qt

In [2]:
from figshare.figshare import Figshare
fshare = Figshare()

article_ids = [14959449] 
sess=['Dlx1']                                  
for id,s in zip(article_ids,sess):
    datapath = os.path.join('Downloaded_data', f'{s}')
    if os.path.isdir(datapath):
        print("Data already exists. Moving on.")
    else:
        print("Downloading data... Please wait, this might take up some time")        # Can take up to 10 minutes
        fshare.retrieve_files_from_article(id,directory=datapath)
        print("Data downloaded!")

Data already exists. Moving on.


In [3]:
path=os.path.join('Downloaded_data','Dlx1','figshare_14959449')

sf, expName, ref_channels, dead_channels = aux_fcn.load_info(path)
channels_map = aux_fcn.load_channels_map(path)

# Reformat channels into correct values
channels, shanks, ref_channels = aux_fcn.reformat_channels(channels_map, ref_channels)
# Read .dat
print('Channel map value: ',channels)
LFP = aux_fcn.load_raw_data(path, expName, channels, verbose=True)
print('Sampling frequency: ', sf)
print('Shape of the original data',LFP.shape)
print(channels_map)

Channel map value:  [0, 1, 2, 3, 4, 5, 6, 7]
Downloaded_data\Dlx1\figshare_14959449/lfp_Dlx1-2021-02-12_12-46-54.dat
fileStart  0
fileStop  490242048
nSamples  245121024
nSamplesPerChannel  30640128
nSamplesPerChunk  10000
size data  30640128
Sampling frequency:  30000
Shape of the original data (30640128, 8)
[[1 1 2]
 [2 1 2]
 [3 1 2]
 [4 1 2]
 [5 1 2]
 [6 1 2]
 [7 1 2]
 [8 1 2]]


In [6]:
prob, LFP_norm = rippl_AI.predict(LFP, sf)

Downsampling data from 30000 to 1250 Hz...
Shape of downsampled data: (1276672, 8)
Normalizing data...
CNN1D_1_Ch8_W60_Ts16_OGmodel12
2494/2494 [==============================] - 1s 462us/step


In [7]:
# An interactive GUI will be displayed, choose your deired threshold
det_ind=rippl_AI.get_intervals(prob,LFP_norm=LFP_norm) 
print(f"{det_ind.shape[0]} events where detected")

230 events where detected


# Try on Allen data

In [ ]:
allen_dat_path = r"F:\GitHub\rippl-AI\allen_data\lfp_use_719161530_729445648.npy"
sr = 1250
import numpy as np

allen_LFP = np.load(allen_dat_path)
print(allen_LFP.shape)
# run prediction on the Allen data
prob,LFP_norm=rippl_AI.predict(allen_LFP,sr) 

(12081228, 8)


In [10]:
# An interactive GUI will be displayed, choose your deired threshold
det_ind=rippl_AI.get_intervals(prob,LFP_norm=LFP_norm) 
print(f"{det_ind.shape[0]} events where detected")

3629 events where detected


# Allen data different session (better quality?)